// Rich, bilingual primary-school curriculum.
// Each subject has 10 topics, each with a definition, an explanation, and 3 worked examples.
// Kept in one file so it's easy for the team to extend.

import type { Lang } from "@/lib/prefs";

export type Bi = { en: string; fr: string };
export type BiList = { en: string[]; fr: string[] };

export type Topic = {
  title: Bi;
  definition: Bi;
  explanation: Bi;
  examples: BiList;
  minutes: number;
};

export type RichSubject = {
  slug: string;
  title: Bi;
  blurb: Bi;
  topics: Topic[];
};

export const pickLang = (b: Bi | undefined, lang: Lang): string => (b ? b[lang] || b.en : "");
export const pickList = (b: BiList | undefined, lang: Lang): string[] => (b ? b[lang] || b.en : []);

// helper to keep declarations short
const T = (
  en_t: string, fr_t: string,
  en_d: string, fr_d: string,
  en_e: string, fr_e: string,
  ex_en: string[], ex_fr: string[],
  minutes = 8,
): Topic => ({
  title: { en: en_t, fr: fr_t },
  definition: { en: en_d, fr: fr_d },
  explanation: { en: en_e, fr: fr_e },
  examples: { en: ex_en, fr: ex_fr },
  minutes,
});

export const richSubjects: RichSubject[] = [
  {
    slug: "languages",
    title: { en: "Languages (English & French)", fr: "Langues (anglais et français)" },
    blurb: { en: "Two tongues, one calm voice — playful bilingual practice.", fr: "Deux langues, une voix calme — pratique bilingue ludique." },
    topics: [
      T("Greetings: Hello / Bonjour", "Salutations : Hello / Bonjour",
        "A greeting is a short, friendly word we use when we meet someone.", "Une salutation est un petit mot amical que l'on dit quand on rencontre quelqu'un.",
        "Greetings open a conversation and tell the other person we see them. They change with the time of day and how well we know the person.", "Les salutations ouvrent la conversation et montrent qu'on remarque l'autre. Elles changent selon le moment et la personne.",
        ["Morning: Good morning / Bonjour", "Afternoon: Good afternoon / Bon après-midi", "Friend: Hi! / Salut !"],
        ["Matin : Good morning / Bonjour", "Après-midi : Good afternoon / Bon après-midi", "Ami : Hi! / Salut !"], 6),
      T("Family names", "Les membres de la famille",
        "Family names are the words for the people who live or grow with us.", "Les noms de famille désignent les personnes qui vivent ou grandissent avec nous.",
        "Naming each person helps us tell our story. The same person can have many names in different languages.", "Nommer chaque personne aide à raconter notre histoire. La même personne a souvent plusieurs noms selon la langue.",
        ["Mother → Mum / Maman", "Father → Dad / Papa", "Sibling → Brother–Sister / Frère–Sœur"],
        ["Mère → Mum / Maman", "Père → Dad / Papa", "Fratrie → Brother–Sister / Frère–Sœur"]),
      T("Colours and numbers 1–10", "Couleurs et nombres 1–10",
        "Colours name what we see; numbers count what we have.", "Les couleurs nomment ce qu'on voit ; les nombres comptent ce qu'on a.",
        "We pair colours with objects and numbers with fingers so the brain has something to hold on to.", "On associe les couleurs à des objets et les nombres aux doigts pour aider la mémoire.",
        ["Red / Rouge — an apple", "Blue / Bleu — the sky", "Three / Trois — three fingers up"],
        ["Red / Rouge — une pomme", "Blue / Bleu — le ciel", "Three / Trois — trois doigts levés"]),
      T("Days of the week", "Les jours de la semaine",
        "The days of the week are the seven names that mark our weekly rhythm.", "Les jours de la semaine sont les sept noms qui rythment notre semaine.",
        "Knowing the days helps a child anticipate routines: school days, rest days, special days.", "Connaître les jours aide à anticiper les routines : école, repos, jours spéciaux.",
        ["Monday / Lundi — school begins", "Saturday / Samedi — market day", "Sunday / Dimanche — family time"],
        ["Monday / Lundi — l'école commence", "Saturday / Samedi — jour du marché", "Sunday / Dimanche — temps en famille"]),
      T("Asking for help", "Demander de l'aide",
        "Asking for help is using words or signs to say we need someone.", "Demander de l'aide, c'est utiliser des mots ou des signes pour dire qu'on a besoin de quelqu'un.",
        "Polite requests stay short and clear. A please at the end makes the message warm.", "Une demande polie reste courte et claire. Un please / s'il te plaît la rend chaleureuse.",
        ["Help me, please / Aide-moi, s'il te plaît", "I don't understand / Je ne comprends pas", "Can you show me? / Peux-tu me montrer ?"],
        ["Aide-moi, s'il te plaît / Help me, please", "Je ne comprends pas / I don't understand", "Peux-tu me montrer ? / Can you show me?"]),
      T("Reading a short bilingual story", "Lire une courte histoire bilingue",
        "A bilingual story tells the same events with two languages side by side.", "Une histoire bilingue raconte les mêmes événements dans deux langues côte à côte.",
        "Reading the two versions together strengthens vocabulary in both languages without translation pressure.", "Lire les deux versions ensemble enrichit le vocabulaire dans les deux langues sans pression de traduction.",
        ["Pick a 4-page picture book", "Read the EN page, then the FR page", "Point to one new word per page"],
        ["Choisir un album de 4 pages", "Lire la page EN, puis la page FR", "Pointer un mot nouveau par page"], 10),
      T("Songs and rhymes", "Chansons et comptines",
        "Songs and rhymes are short musical texts that repeat sounds and rhythm.", "Les chansons et comptines sont de courts textes musicaux qui répètent des sons et un rythme.",
        "Music carries words further than speech alone, so new words stay longer in memory.", "La musique porte les mots plus loin que la parole seule, et la mémoire les garde mieux.",
        ["Twinkle Twinkle / Brille brille petite étoile", "Head, shoulders, knees and toes", "Frère Jacques / Are you sleeping?"],
        ["Twinkle Twinkle / Brille brille petite étoile", "Head, shoulders, knees and toes", "Frère Jacques / Are you sleeping?"], 6),
      T("Words for feelings", "Les mots des émotions",
        "Feeling words let us name what is happening inside our body.", "Les mots des émotions nomment ce qui se passe dans notre corps.",
        "When a child can say happy or angry, the body softens because the feeling has been heard.", "Quand l'enfant peut dire heureux ou en colère, le corps s'apaise parce que l'émotion a été entendue.",
        ["Happy / Heureux", "Tired / Fatigué", "Excited / Excité"],
        ["Happy / Heureux", "Tired / Fatigué", "Excited / Excité"]),
      T("Polite words", "Les mots polis",
        "Polite words are small words that show care for others.", "Les mots polis sont de petits mots qui montrent qu'on prend soin des autres.",
        "Using them is a habit, not a test. Modelled often, they appear naturally.", "Les utiliser est une habitude, pas un examen. Bien modelés, ils viennent naturellement.",
        ["Please / S'il te plaît", "Thank you / Merci", "Sorry / Pardon"],
        ["Please / S'il te plaît", "Thank you / Merci", "Sorry / Pardon"]),
      T("Telling a tiny story", "Raconter une petite histoire",
        "A tiny story has a beginning, a middle and an end in just three sentences.", "Une petite histoire a un début, un milieu et une fin en trois phrases.",
        "This shape teaches the brain to organise events in time before writing long texts.", "Cette structure entraîne le cerveau à organiser les événements avant d'écrire de longs textes.",
        ["I went to the market.", "I saw a yellow mango.", "I ate it at home."],
        ["Je suis allé au marché.", "J'ai vu une mangue jaune.", "Je l'ai mangée à la maison."], 10),
    ],
  },
  {
    slug: "arithmetic",
    title: { en: "Arithmetic", fr: "Arithmétique" },
    blurb: { en: "Number sense built through soft, repeatable patterns.", fr: "Le sens du nombre construit par des motifs doux et répétables." },
    topics: [
      T("Counting 1 to 20", "Compter de 1 à 20",
        "Counting is saying numbers in order while pointing to one object at a time.", "Compter, c'est dire les nombres dans l'ordre en pointant un objet à la fois.",
        "One number for one object is called one-to-one matching. It is the base for all arithmetic.", "Un nombre pour un objet : c'est la correspondance terme à terme. C'est la base de toute l'arithmétique.",
        ["Count 5 stones in a bowl", "Count steps up the stairs", "Count claps in a song"],
        ["Compter 5 cailloux dans un bol", "Compter les marches d'escalier", "Compter les claquements dans une chanson"], 6),
      T("Comparing: more, less, equal", "Comparer : plus, moins, autant",
        "Comparing means looking at two groups to see which has more, less, or the same.", "Comparer, c'est regarder deux groupes pour voir lequel a plus, moins ou autant.",
        "We line up the objects two by two. Whichever line ends first has less.", "On aligne les objets deux par deux. La ligne qui se termine en premier en a moins.",
        ["4 apples vs 6 apples → 6 is more", "3 cars vs 3 cars → equal", "8 vs 5 → 5 is less"],
        ["4 pommes contre 6 pommes → 6 c'est plus", "3 voitures contre 3 voitures → autant", "8 contre 5 → 5 c'est moins"]),
      T("Addition up to 10", "Addition jusqu'à 10",
        "Addition is putting two groups together to find the total.", "L'addition, c'est réunir deux groupes pour trouver le total.",
        "We use the symbol +. The answer is called the sum. With small numbers, fingers are perfect tools.", "On utilise le signe +. Le résultat s'appelle la somme. Avec de petits nombres, les doigts suffisent.",
        ["2 + 3 = 5", "4 + 4 = 8", "6 + 1 = 7"],
        ["2 + 3 = 5", "4 + 4 = 8", "6 + 1 = 7"]),
      T("Subtraction up to 10", "Soustraction jusqu'à 10",
        "Subtraction is taking some away from a group to see what is left.", "La soustraction, c'est enlever d'un groupe pour voir ce qui reste.",
        "We use the symbol −. The answer is called the difference. Stories help: I had, I gave, I have.", "On utilise le signe −. Le résultat s'appelle la différence. Les histoires aident : j'avais, j'ai donné, il reste.",
        ["5 − 2 = 3", "7 − 4 = 3", "10 − 6 = 4"],
        ["5 − 2 = 3", "7 − 4 = 3", "10 − 6 = 4"]),
      T("Shapes around us", "Les formes autour de nous",
        "Shapes are the outlines we see in objects: circles, squares, triangles, rectangles.", "Les formes sont les contours qu'on voit dans les objets : cercles, carrés, triangles, rectangles.",
        "Naming shapes trains the eye for geometry and reading later on.", "Nommer les formes entraîne l'œil pour la géométrie et pour la lecture plus tard.",
        ["Plate → circle / cercle", "Window → rectangle", "Roof → triangle"],
        ["Assiette → cercle", "Fenêtre → rectangle", "Toit → triangle"]),
      T("Patterns", "Les motifs",
        "A pattern is something that repeats in a predictable way.", "Un motif, c'est quelque chose qui se répète de façon prévisible.",
        "Spotting patterns is the first step of algebra. Children love it because the brain predicts what comes next.", "Repérer les motifs, c'est le premier pas vers l'algèbre. Le cerveau adore prédire la suite.",
        ["Red, blue, red, blue, ?", "Clap, stomp, clap, stomp, ?", "1, 2, 1, 2, 1, ?"],
        ["Rouge, bleu, rouge, bleu, ?", "Tape, frappe, tape, frappe, ?", "1, 2, 1, 2, 1, ?"]),
      T("Place value: tens and units", "Les dizaines et les unités",
        "Place value tells us what a digit means depending on where it sits.", "La valeur de position dit ce qu'un chiffre signifie selon sa place.",
        "In 23, the 2 means two tens (20) and the 3 means three units. Bundles of ten sticks make this visible.", "Dans 23, le 2 vaut deux dizaines (20) et le 3 vaut trois unités. Des bottes de dix bâtons le rendent visible.",
        ["12 = 1 ten + 2 units", "35 = 3 tens + 5 units", "70 = 7 tens + 0 units"],
        ["12 = 1 dizaine + 2 unités", "35 = 3 dizaines + 5 unités", "70 = 7 dizaines + 0 unités"]),
      T("Times tables: 2 and 5", "Tables de multiplication : 2 et 5",
        "A times table is a repeating addition of the same number.", "Une table de multiplication est une addition répétée du même nombre.",
        "2× and 5× are friendliest because they appear in pairs (eyes, hands) and in fingers of one hand.", "Les tables de 2 et 5 sont les plus amicales : paires (yeux, mains) et doigts d'une main.",
        ["2 × 3 = 6 (3 pairs of shoes)", "5 × 4 = 20 (4 hands of fingers)", "2 × 7 = 14"],
        ["2 × 3 = 6 (3 paires de chaussures)", "5 × 4 = 20 (4 mains de doigts)", "2 × 7 = 14"]),
      T("Measuring length", "Mesurer la longueur",
        "Measuring length is finding how long something is using a unit.", "Mesurer la longueur, c'est trouver combien quelque chose est long avec une unité.",
        "We can use feet, hands or a ruler. The unit must be the same from start to end.", "On peut utiliser les pieds, les mains ou une règle. L'unité doit rester la même du début à la fin.",
        ["Table = 6 hands long", "Pencil = 15 cm", "Room = 8 footsteps"],
        ["Table = 6 mains de long", "Crayon = 15 cm", "Pièce = 8 pas"]),
      T("Money for small shopping", "L'argent pour les petits achats",
        "Money is a tool we exchange for goods and services.", "L'argent est un outil qu'on échange contre des biens et des services.",
        "Counting coins teaches addition with a real-life purpose, and giving change teaches subtraction.", "Compter les pièces enseigne l'addition avec un but réel, et rendre la monnaie enseigne la soustraction.",
        ["Bread = 200 — pay 500 — change 300", "Two mangoes at 100 each = 200", "Save 50 each day for 10 days = 500"],
        ["Pain = 200 — payer 500 — rendre 300", "Deux mangues à 100 chacune = 200", "Garder 50 par jour pendant 10 jours = 500"]),
    ],
  },
  {
    slug: "writing",
    title: { en: "Writing", fr: "Écriture" },
    blurb: { en: "Pencil grip, letters, words — one calm stroke at a time.", fr: "La tenue du crayon, lettres, mots — un trait calme à la fois." },
    topics: [
      T("How to hold a pencil", "Comment tenir un crayon",
        "Pencil grip is the way fingers hold the tool so writing is comfortable.", "La tenue du crayon est la façon dont les doigts tiennent l'outil pour écrire confortablement.",
        "Thumb and index pinch, middle finger supports, the other two rest. A short pencil teaches the grip faster.", "Pouce et index pincent, le majeur soutient, les deux autres se reposent. Un crayon court aide à apprendre vite.",
        ["Pinch with thumb + index", "Rest on middle finger", "Use a short pencil for practice"],
        ["Pincer avec pouce + index", "Poser sur le majeur", "Utiliser un crayon court pour s'entraîner"], 6),
      T("Pre-writing lines and curves", "Traits et courbes préparatoires",
        "These are simple strokes that train the hand before letters.", "Ce sont des traits simples qui entraînent la main avant les lettres.",
        "Straight, slanted, curved and looped strokes build all the alphabet.", "Les traits droits, obliques, courbes et bouclés forment tout l'alphabet.",
        ["Vertical lines | | |", "Curves like c c c", "Spirals ⟲ ⟲"],
        ["Traits verticaux | | |", "Courbes c c c", "Spirales ⟲ ⟲"]),
      T("The alphabet in order", "L'alphabet dans l'ordre",
        "The alphabet is the set of letters used to write our languages.", "L'alphabet est l'ensemble des lettres qui servent à écrire nos langues.",
        "Knowing the order helps with dictionaries, lists and games. Singing it locks the order in memory.", "Connaître l'ordre aide pour les dictionnaires, les listes et les jeux. Chanter aide à mémoriser.",
        ["Sing A to Z", "Find letters around the room", "Trace each letter once a day"],
        ["Chanter A à Z", "Trouver les lettres dans la pièce", "Tracer chaque lettre une fois par jour"]),
      T("Writing my name", "Écrire mon prénom",
        "Your name is the very first word the hand should master.", "Le prénom est le tout premier mot que la main doit maîtriser.",
        "Start with capitals, then move to lower case. Repeat in different colours to keep it joyful.", "Commencer par les majuscules, puis les minuscules. Répéter en couleurs pour garder le plaisir.",
        ["AMINA — capitals", "Amina — capital + lowercase", "Write name on a drawing"],
        ["AMINA — en majuscules", "Amina — majuscule + minuscules", "Écrire son prénom sur un dessin"]),
      T("Capital and lowercase letters", "Majuscules et minuscules",
        "Capitals are the big letters; lowercase are the small ones.", "Les majuscules sont les grandes lettres, les minuscules les petites.",
        "Capitals start sentences and proper names. Lowercase fill the rest of the words.", "Les majuscules commencent les phrases et les noms propres. Les minuscules remplissent le reste.",
        ["Paris starts with P", "I always write I in capital", "dog is all lowercase"],
        ["Paris commence par P", "I s'écrit toujours en majuscule", "chien est tout en minuscules"]),
      T("Spaces between words", "Les espaces entre les mots",
        "A space is the small gap we leave so words can be told apart.", "Un espace est le petit blanc qu'on laisse pour séparer les mots.",
        "One finger-width is a good rhythm. Without spaces, sentences become a long line of letters.", "La largeur d'un doigt est un bon rythme. Sans espaces, la phrase devient une longue ligne de lettres.",
        ["I likemango → I like mango", "Use a finger as a space", "Read aloud to find missing spaces"],
        ["J'aimemangue → J'aime mangue", "Utiliser un doigt comme espace", "Lire à voix haute pour trouver les espaces manquants"]),
      T("A sentence with a full stop", "Une phrase avec un point",
        "A sentence is a complete thought. A full stop tells the reader to stop.", "Une phrase est une pensée complète. Le point indique au lecteur d'arrêter.",
        "Capital letter at the start, full stop at the end. That frame holds the meaning.", "Majuscule au début, point à la fin. Ce cadre porte le sens.",
        ["Mum is cooking rice.", "I play with my brother.", "The sun is bright."],
        ["Maman cuit le riz.", "Je joue avec mon frère.", "Le soleil est éclatant."]),
      T("Question and exclamation marks", "Points d'interrogation et d'exclamation",
        "These marks tell the reader if a sentence is a question or a strong feeling.", "Ces signes indiquent une question ou une émotion forte.",
        "A question mark goes after a question. An exclamation mark shows surprise, joy or warning.", "Le point d'interrogation suit une question. Le point d'exclamation marque la surprise, la joie ou un avertissement.",
        ["What is your name?", "How beautiful!", "Watch out!"],
        ["Comment t'appelles-tu ?", "Comme c'est beau !", "Attention !"]),
      T("Writing a short note", "Écrire un petit mot",
        "A short note shares one idea with one person.", "Un petit mot transmet une idée à une personne.",
        "Greeting on top, the message, then your name. Three lines is enough.", "Salutation en haut, le message, puis le prénom. Trois lignes suffisent.",
        ["Dear Mum, I love you. — Amina", "Hi Sam, see you at school. — Pip", "Thank you for the gift. — Tom"],
        ["Chère Maman, je t'aime. — Amina", "Salut Sam, à l'école. — Pip", "Merci pour le cadeau. — Tom"]),
      T("My day in three sentences", "Ma journée en trois phrases",
        "This is a tiny diary: what I did, what I felt, what I learned.", "C'est un petit journal : ce que j'ai fait, ressenti, appris.",
        "Three sentences keep writing kind. Over time, they become memory.", "Trois phrases gardent l'écriture douce. Avec le temps, elles deviennent mémoire.",
        ["I went to school.", "I felt happy at lunch.", "I learned a new word."],
        ["Je suis allé à l'école.", "J'étais content au déjeuner.", "J'ai appris un mot nouveau."], 10),
    ],
  },
  {
    slug: "reading",
    title: { en: "Reading", fr: "Lecture" },
    blurb: { en: "From sounds to stories, never rushed.", fr: "Des sons aux histoires, sans précipitation." },
    topics: [
      T("Letter sounds (phonics)", "Les sons des lettres (phonétique)",
        "Phonics is the link between a letter and the sound it makes.", "La phonétique relie la lettre au son qu'elle produit.",
        "Each letter has a name and a sound. The sound is what we use to read words.", "Chaque lettre a un nom et un son. C'est le son qui sert à lire.",
        ["B says /b/ — ball", "M says /m/ — mum", "S says /s/ — sun"],
        ["B fait /b/ — ballon", "M fait /m/ — maman", "S fait /s/ — soleil"], 6),
      T("Vowels and consonants", "Voyelles et consonnes",
        "Vowels are a, e, i, o, u, y. Everything else is a consonant.", "Les voyelles sont a, e, i, o, u, y. Tout le reste est une consonne.",
        "Vowels are open sounds: the air flows freely. Consonants block the air with lips, teeth or tongue.", "Les voyelles sont des sons ouverts : l'air passe librement. Les consonnes bloquent l'air avec les lèvres, les dents ou la langue.",
        ["A — open mouth", "M — closed lips", "T — tongue taps the teeth"],
        ["A — bouche ouverte", "M — lèvres fermées", "T — la langue tape les dents"]),
      T("Blending simple words", "Assembler des mots simples",
        "Blending is gliding sounds together to read a word.", "Assembler, c'est glisser les sons ensemble pour lire un mot.",
        "We say each sound, then we run them together: c-a-t → cat.", "On dit chaque son, puis on les enchaîne : c-a-t → cat.",
        ["c-a-t → cat", "s-u-n → sun", "m-a-p → map"],
        ["c-a-t → cat", "s-u-n → sun", "m-a-p → map"]),
      T("Sight words", "Les mots fréquents",
        "Sight words appear so often that we learn them as a whole shape.", "Les mots fréquents reviennent si souvent qu'on les reconnaît globalement.",
        "Reading sight words quickly makes sentences flow. We meet them in almost every page.", "Les lire vite donne de la fluidité. On les trouve sur presque chaque page.",
        ["the / le", "and / et", "is / est"],
        ["the / le", "and / et", "is / est"]),
      T("Reading aloud with rhythm", "Lire à voix haute avec rythme",
        "Reading aloud is saying the words while keeping the music of the sentence.", "Lire à voix haute, c'est dire les mots en gardant la musique de la phrase.",
        "Pauses for commas, drop for full stops. The reader's voice tells the story as much as the words.", "Pauses aux virgules, baisse de voix aux points. La voix raconte autant que les mots.",
        ["Pause at each ,", "Drop voice at each .", "Lift voice at ?"],
        ["Pause à chaque ,", "Baisser la voix au .", "Monter la voix au ?"]),
      T("Understanding a picture book", "Comprendre un album",
        "A picture book tells a story with words and images that complete each other.", "Un album raconte une histoire avec des mots et des images qui se complètent.",
        "Children can read the pictures before they can read the text — both are valid.", "L'enfant peut lire les images avant le texte — les deux sont valides.",
        ["Who is the main character?", "Where does it happen?", "How does it end?"],
        ["Qui est le héros ?", "Où se passe l'histoire ?", "Comment finit-elle ?"]),
      T("Asking questions about a story", "Poser des questions sur une histoire",
        "Questions are the way the mind talks back to a story.", "Les questions sont la façon dont l'esprit dialogue avec l'histoire.",
        "Open questions (why, how) build comprehension; closed ones (yes/no) build recall.", "Les questions ouvertes (pourquoi, comment) construisent la compréhension ; les fermées (oui/non) la mémoire.",
        ["Why is she sad?", "What would you do?", "Did the dog come home?"],
        ["Pourquoi est-elle triste ?", "Et toi, que ferais-tu ?", "Le chien est-il rentré ?"]),
      T("Beginning, middle and end", "Début, milieu et fin",
        "Stories have three parts so the mind can follow them.", "Les histoires ont trois parties pour que l'esprit puisse les suivre.",
        "The beginning sets the scene; the middle brings the problem; the end brings a change.", "Le début pose le décor ; le milieu apporte le problème ; la fin apporte un changement.",
        ["Begin: A boy finds a kite", "Middle: It flies away", "End: A friend brings it back"],
        ["Début : Un garçon trouve un cerf-volant", "Milieu : Il s'envole", "Fin : Un ami le rapporte"]),
      T("Reading signs around us", "Lire les panneaux autour de nous",
        "Signs are short words and pictures that guide us in the world.", "Les panneaux sont des mots et images courts qui nous guident dans le monde.",
        "Reading them is real-life reading: shop names, road signs, food labels.", "Les lire, c'est lire dans la vraie vie : magasins, panneaux, étiquettes.",
        ["STOP at a road", "EXIT at school", "OPEN on a shop door"],
        ["STOP sur la route", "SORTIE à l'école", "OUVERT sur une boutique"]),
      T("A short story together", "Une courte histoire ensemble",
        "Reading together turns a story into a shared moment.", "Lire ensemble transforme une histoire en moment partagé.",
        "Take turns: one page each. Re-read favourite parts without rushing.", "À tour de rôle : une page chacun. Relire ses passages préférés sans se presser.",
        ["You read 1 page, I read 1 page", "Re-read the funny part", "Talk about the best moment"],
        ["Tu lis 1 page, je lis 1 page", "Relire le passage drôle", "Parler du meilleur moment"], 12),
    ],
  },
  {
    slug: "art",
    title: { en: "Art & Craft", fr: "Arts plastiques" },
    blurb: { en: "Hands, colours and texture as quiet self-expression.", fr: "Les mains, les couleurs et la matière comme expression calme." },
    topics: [
      T("Primary colours", "Les couleurs primaires",
        "Primary colours are the three you can't make by mixing others: red, yellow, blue.", "Les couleurs primaires sont les trois qu'on ne peut pas obtenir en mélangeant : rouge, jaune, bleu.",
        "All other colours come from these three. They are the heart of every paint box.", "Toutes les autres couleurs viennent d'elles. C'est le cœur de chaque boîte de peinture.",
        ["Red — tomato", "Yellow — sun", "Blue — sea"],
        ["Rouge — tomate", "Jaune — soleil", "Bleu — mer"]),
      T("Mixing secondary colours", "Mélanger les couleurs secondaires",
        "Secondary colours come from mixing two primaries.", "Les couleurs secondaires viennent du mélange de deux primaires.",
        "Try it on a plate: a dot of one, a dot of another, stir gently and a new colour appears.", "À tester sur une assiette : une touche de chacune, mélanger doucement, une nouvelle couleur apparaît.",
        ["Red + yellow = orange", "Blue + yellow = green", "Red + blue = purple"],
        ["Rouge + jaune = orange", "Bleu + jaune = vert", "Rouge + bleu = violet"]),
      T("Lines and shapes", "Lignes et formes",
        "Drawing is made of lines (paths of the pencil) and shapes (closed lines).", "Le dessin est fait de lignes (traces du crayon) et de formes (lignes fermées).",
        "Short, long, straight, wavy: each line has its own feeling.", "Court, long, droit, ondulé : chaque ligne porte une émotion.",
        ["Wavy line = water", "Straight line = floor", "Closed circle = sun"],
        ["Ligne ondulée = eau", "Ligne droite = sol", "Cercle fermé = soleil"]),
      T("Drawing a face", "Dessiner un visage",
        "A face has shapes for the head, eyes, nose and mouth.", "Un visage a des formes pour la tête, les yeux, le nez et la bouche.",
        "Start with an oval, place two eyes in the middle, the nose halfway down, the mouth below.", "Commencer par un ovale, deux yeux au milieu, le nez à mi-chemin, la bouche en dessous.",
        ["Oval head", "Two dots for eyes", "Curved smile"],
        ["Ovale pour la tête", "Deux points pour les yeux", "Sourire courbé"]),
      T("Drawing my family", "Dessiner ma famille",
        "Family portraits show who lives with us and how we feel about them.", "Le portrait de famille montre qui vit avec nous et ce qu'on ressent.",
        "There is no wrong size or order. Tall, small, distance, colours all tell a real story.", "Pas de bonne taille ni d'ordre. Hauteur, distance, couleurs racontent une vraie histoire.",
        ["Draw each person", "Add names", "Add a heart for the one you miss"],
        ["Dessiner chaque personne", "Ajouter les prénoms", "Un cœur pour celle qui te manque"]),
      T("Paper folding (origami simple)", "Pliage de papier (origami simple)",
        "Folding paper turns a flat sheet into a 3D shape.", "Plier le papier transforme une feuille en forme 3D.",
        "Crease firmly, open carefully. Each fold should match the corners.", "Marquer le pli fermement, ouvrir doucement. Chaque pli doit aligner les coins.",
        ["Fold into a triangle", "Fold a paper boat", "Make a paper fan"],
        ["Plier en triangle", "Plier un bateau en papier", "Fabriquer un éventail"]),
      T("Collage with paper and leaves", "Collage avec papier et feuilles",
        "Collage is the art of gluing pieces together to make a new image.", "Le collage est l'art de coller des morceaux pour faire une nouvelle image.",
        "Mix textures: smooth paper, rough leaves, soft cloth. Touch matters as much as sight.", "Mélanger les textures : papier lisse, feuilles rugueuses, tissu doux. Le toucher compte autant que la vue.",
        ["Glue leaves as a tree", "Tear paper into clouds", "Add buttons as flowers"],
        ["Coller des feuilles en arbre", "Déchirer du papier en nuages", "Ajouter des boutons en fleurs"]),
      T("Modelling with clay or dough", "Modeler avec de l'argile ou de la pâte",
        "Modelling uses the hands to give soft material a shape.", "Le modelage utilise les mains pour donner forme à une matière souple.",
        "Roll, pinch, press, smooth. The fingers learn while the mind rests.", "Rouler, pincer, presser, lisser. Les doigts apprennent pendant que l'esprit se repose.",
        ["Roll a snake", "Pinch a small bowl", "Shape an apple"],
        ["Rouler un serpent", "Pincer un petit bol", "Modeler une pomme"]),
      T("Looking at a painting", "Regarder une peinture",
        "Looking at art is asking what we see and what we feel.", "Regarder l'art, c'est se demander ce qu'on voit et ce qu'on ressent.",
        "Notice colours first, then shapes, then the mood. There is no wrong answer.", "On regarde d'abord les couleurs, puis les formes, puis l'ambiance. Pas de mauvaise réponse.",
        ["Which colour stands out?", "What shapes can you find?", "Is it calm or busy?"],
        ["Quelle couleur ressort ?", "Quelles formes vois-tu ?", "C'est calme ou animé ?"]),
      T("Showing my art", "Présenter mon œuvre",
        "Sharing art is saying what we made and why we liked making it.", "Présenter son œuvre, c'est dire ce qu'on a fait et pourquoi on a aimé le faire.",
        "Two sentences are enough. Confidence grows with kind audiences.", "Deux phrases suffisent. La confiance grandit avec un public bienveillant.",
        ["This is my house", "I used blue because it is calm", "I am proud of the roof"],
        ["C'est ma maison", "J'ai pris du bleu parce que c'est calme", "Je suis fier du toit"]),
    ],
  },
  {
    slug: "music",
    title: { en: "Music", fr: "Musique" },
    blurb: { en: "Sound as friend, not stimulus.", fr: "Le son comme ami, pas comme stimulus." },
    topics: [
      T("Loud and quiet", "Fort et doux",
        "Volume is how loud or soft a sound is.", "Le volume, c'est l'intensité d'un son : fort ou doux.",
        "Soft sounds invite focus; loud sounds invite movement. We can choose what we need.", "Les sons doux invitent à se concentrer ; les sons forts à bouger. On choisit selon le besoin.",
        ["Whisper a name", "Clap softly, then loud", "Hum / shout the same note"],
        ["Chuchoter un prénom", "Taper doucement puis fort", "Fredonner / crier la même note"]),
      T("Fast and slow (tempo)", "Vite et lent (tempo)",
        "Tempo is how fast or slow a beat goes.", "Le tempo, c'est la vitesse du battement.",
        "Slow tempo calms the body; fast tempo wakes it up. Tempo helps us regulate energy.", "Un tempo lent calme le corps ; un tempo rapide le réveille. Le tempo aide à réguler l'énergie.",
        ["Slow walking song", "Fast running song", "Clap from slow to fast"],
        ["Chanson de marche lente", "Chanson de course rapide", "Taper du lent au rapide"]),
      T("High and low (pitch)", "Aigu et grave (hauteur)",
        "Pitch is how high or low a note sounds.", "La hauteur, c'est si la note est aiguë ou grave.",
        "Birds sing high, drums boom low. The voice can travel between them like an elevator.", "Les oiseaux chantent aigu, les tambours grondent grave. La voix monte et descend comme un ascenseur.",
        ["Sing like a bird (high)", "Sing like a frog (low)", "Slide up then down"],
        ["Chanter comme un oiseau (aigu)", "Chanter comme une grenouille (grave)", "Glisser de l'aigu au grave"]),
      T("Beat and clapping", "Le rythme et taper dans les mains",
        "A beat is the steady heart of music.", "Le rythme, c'est le cœur régulier de la musique.",
        "Tap a steady pulse with your hands or feet — that is the beat.", "Tape une pulsation régulière avec les mains ou les pieds — c'est le rythme.",
        ["Tap on knees in fours", "Walk on the beat", "Clap a song you know"],
        ["Taper sur les genoux à 4 temps", "Marcher sur le rythme", "Taper une chanson connue"]),
      T("Simple rhythms", "Rythmes simples",
        "A rhythm is a small pattern of long and short sounds.", "Un rythme est un petit motif de sons longs et courts.",
        "We can write rhythms with words like ta (long) and ti-ti (short).", "On écrit les rythmes avec ta (long) et ti-ti (court).",
        ["ta — ta — ta", "ti-ti — ta", "ta — ti-ti — ta"],
        ["ta — ta — ta", "ti-ti — ta", "ta — ti-ti — ta"]),
      T("Singing together", "Chanter ensemble",
        "Group singing is matching voices and breath with others.", "Chanter en groupe, c'est accorder voix et respiration avec les autres.",
        "We breathe in together, we start together. Listening matters as much as singing.", "On respire ensemble, on démarre ensemble. Écouter compte autant que chanter.",
        ["Sing a familiar lullaby", "Echo songs (call & response)", "Round: Frère Jacques"],
        ["Chanter une berceuse connue", "Chanson en écho (appel/réponse)", "Canon : Frère Jacques"]),
      T("Instruments around us", "Les instruments autour de nous",
        "Anything that makes a controlled sound can be an instrument.", "Tout ce qui produit un son maîtrisé peut être un instrument.",
        "A pot becomes a drum, a comb becomes a kazoo, a bottle becomes a flute.", "Une casserole devient un tambour, un peigne un kazoo, une bouteille une flûte.",
        ["Pot + spoon = drum", "Rice in a bottle = shaker", "Glass with water = chime"],
        ["Casserole + cuillère = tambour", "Riz dans une bouteille = shaker", "Verre d'eau = carillon"]),
      T("Music from many places", "Des musiques du monde",
        "Every place on earth has its own songs and instruments.", "Chaque lieu sur Terre a ses chansons et ses instruments.",
        "Listening to different music opens the ear and the heart.", "Écouter d'autres musiques ouvre l'oreille et le cœur.",
        ["Kora from West Africa", "Drums from Burundi", "Lullabies from many homes"],
        ["Kora d'Afrique de l'Ouest", "Tambours du Burundi", "Berceuses de plusieurs pays"]),
      T("Music for calming", "La musique pour se calmer",
        "Calming music has a slow beat, soft volume and gentle notes.", "Une musique apaisante a un tempo lent, un faible volume et des notes douces.",
        "Use it at bedtime, after a meltdown, or during homework.", "À utiliser au coucher, après une crise, ou pendant les devoirs.",
        ["Soft piano at bedtime", "Humming together", "Slow lullaby loop"],
        ["Piano doux au coucher", "Fredonner ensemble", "Berceuse en boucle"]),
      T("Listening with care", "Écouter avec attention",
        "Active listening means noticing what is in a sound.", "Écouter activement, c'est remarquer ce qu'il y a dans un son.",
        "We can listen for the instruments, the words and the feeling at the same time.", "On peut écouter les instruments, les paroles et l'émotion en même temps.",
        ["Name 1 instrument you hear", "Find 1 word you understand", "Say how the song makes you feel"],
        ["Nommer 1 instrument entendu", "Trouver 1 mot compris", "Dire ce que la chanson fait ressentir"]),
    ],
  },
  {
    slug: "pe",
    title: { en: "Physical Education (PE)", fr: "Éducation physique (EPS)" },
    blurb: { en: "Movement that fits the body of the day.", fr: "Du mouvement adapté au corps du jour." },
    topics: [
      T("Warm-up", "L'échauffement",
        "Warm-up is the gentle movement we do before sport.", "L'échauffement est le mouvement doux avant le sport.",
        "It wakes the muscles and the heart slowly so we don't get hurt.", "Il réveille muscles et cœur en douceur pour éviter les blessures.",
        ["March on the spot 1 min", "Roll the shoulders", "Touch your toes"],
        ["Marcher sur place 1 min", "Rouler les épaules", "Toucher ses orteils"], 5),
      T("Walking with good posture", "Marcher avec une bonne posture",
        "Good posture means head up, shoulders relaxed, eyes forward.", "Une bonne posture, c'est tête haute, épaules détendues, regard devant.",
        "It keeps breathing easy and the back happy.", "Cela rend la respiration facile et le dos heureux.",
        ["Walk a straight line", "Walk balancing a book", "Walk slow then quick"],
        ["Marcher en ligne droite", "Marcher avec un livre sur la tête", "Marcher lentement puis vite"]),
      T("Running safely", "Courir en sécurité",
        "Running uses bigger steps and stronger breathing than walking.", "Courir, c'est de plus grands pas et une respiration plus forte que la marche.",
        "Look ahead, land softly on the foot, breathe through the nose when possible.", "Regarder devant, poser le pied doucement, respirer par le nez si possible.",
        ["Jog 1 minute", "Sprint 10 metres", "Run a small zig-zag"],
        ["Trotter 1 minute", "Sprint sur 10 mètres", "Courir en petit zigzag"]),
      T("Jumping and hopping", "Sauter et sautiller",
        "Jumping uses both feet; hopping uses one.", "Sauter se fait à deux pieds ; sautiller se fait à un.",
        "These build leg strength and balance. Bend the knees on landing.", "Cela renforce les jambes et l'équilibre. Plier les genoux à l'atterrissage.",
        ["Jump over a rope", "Hop on left, then right", "Star jump 5 times"],
        ["Sauter par-dessus une corde", "Sautiller à gauche puis à droite", "5 sauts en étoile"]),
      T("Balance games", "Jeux d'équilibre",
        "Balance is staying steady on a small support.", "L'équilibre, c'est rester stable sur un petit appui.",
        "Eyes fixed on a point help the body stay still. Arms out act like wings.", "Fixer un point aide le corps. Les bras écartés font comme des ailes.",
        ["Stand on one foot 10 s", "Walk along a line", "Hold a tree pose"],
        ["Tenir sur un pied 10 s", "Marcher sur une ligne", "Tenir la posture de l'arbre"]),
      T("Throwing and catching", "Lancer et attraper",
        "Throwing sends an object; catching brings it back to the hands.", "Lancer envoie un objet ; attraper le ramène aux mains.",
        "Throw under-arm at first; eyes follow the ball, hands form a basket.", "Lancer par en dessous d'abord ; suivre la balle des yeux, faire un panier avec les mains.",
        ["Toss a sock-ball up & catch", "Throw to a partner 1 m", "Bounce-catch off a wall"],
        ["Lancer une balle-chaussette en l'air", "Lancer à un partenaire à 1 m", "Lancer au mur et attraper"]),
      T("Team games and fair play", "Jeux d'équipe et fair-play",
        "A team game needs rules and respect for everyone.", "Un jeu d'équipe a besoin de règles et de respect.",
        "Win kindly, lose kindly; congratulate the other team.", "Gagner gentiment, perdre gentiment ; féliciter l'autre équipe.",
        ["Tag with safe-zones", "Pass-and-run game", "Cheer one teammate by name"],
        ["Loup avec zones sûres", "Passe-et-cours", "Féliciter un coéquipier par son prénom"]),
      T("Flexibility and stretching", "Souplesse et étirements",
        "Stretching makes muscles longer and joints freer.", "S'étirer rend les muscles plus longs et les articulations plus libres.",
        "Stretch slowly until you feel a gentle pull — never pain.", "S'étirer lentement jusqu'à sentir une légère tension — jamais de douleur.",
        ["Reach to the sky 10 s", "Side bend left & right", "Sit and touch toes"],
        ["S'étirer vers le ciel 10 s", "Pencher à gauche et à droite", "Assis, toucher ses orteils"]),
      T("Breathing for sport", "Respirer pour le sport",
        "Sport-breath is deep and steady, not short and panicked.", "La respiration sportive est profonde et régulière, pas courte ni paniquée.",
        "In through the nose, out through the mouth keeps the heart calm.", "Inspirer par le nez, expirer par la bouche garde le cœur calme.",
        ["Box breath: 4-4-4-4", "Belly breath 5 times", "Sigh out slowly"],
        ["Respiration carrée 4-4-4-4", "5 respirations ventrales", "Souffler doucement"]),
      T("Cool-down and rest", "Récupération et repos",
        "Cool-down is the slow finish that lets the body return to calm.", "La récupération, c'est la fin lente qui ramène le corps au calme.",
        "Walk, stretch, drink water. Rest is part of training.", "Marcher, s'étirer, boire de l'eau. Le repos fait partie de l'entraînement.",
        ["Walk slowly 1 min", "Stretch each leg", "Drink water and rest 2 min"],
        ["Marcher lentement 1 min", "Étirer chaque jambe", "Boire de l'eau et se reposer 2 min"], 6),
    ],
  },
  {
    slug: "health-education",
    title: { en: "Health Education", fr: "Éducation à la santé" },
    blurb: { en: "Caring for body and mind, day by day.", fr: "Prendre soin du corps et de l'esprit, jour après jour." },
    topics: [
      T("Hand washing", "Le lavage des mains",
        "Washing hands removes germs we cannot see.", "Se laver les mains enlève les microbes invisibles.",
        "Wet, soap, rub for 20 seconds, rinse, dry. Do it before eating and after the toilet.", "Mouiller, savonner, frotter 20 s, rincer, sécher. À faire avant de manger et après les toilettes.",
        ["Wash before meals", "Wash after the toilet", "Wash after playing outside"],
        ["Se laver avant les repas", "Se laver après les toilettes", "Se laver après avoir joué dehors"], 5),
      T("Brushing teeth", "Se brosser les dents",
        "Brushing protects teeth from sugar and germs.", "Le brossage protège les dents du sucre et des microbes.",
        "Twice a day, two minutes, small circles, all sides — and don't forget the tongue.", "Deux fois par jour, deux minutes, petits cercles, tous les côtés — et la langue.",
        ["Morning + night", "Two minutes", "Spit, don't rinse heavily"],
        ["Matin + soir", "Deux minutes", "Cracher, peu rincer"]),
      T("Healthy plates (food groups)", "L'assiette équilibrée",
        "A healthy plate has many colours and food groups.", "Une assiette équilibrée a plusieurs couleurs et groupes d'aliments.",
        "Half vegetables and fruit, a quarter grains, a quarter protein — water beside.", "Moitié légumes et fruits, un quart céréales, un quart protéines — de l'eau à côté.",
        ["Spinach + rice + fish", "Beans + plantain + greens", "Eggs + bread + tomato"],
        ["Épinards + riz + poisson", "Haricots + plantain + verdure", "Œufs + pain + tomate"]),
      T("Drinking enough water", "Boire assez d'eau",
        "Water keeps the body cool and the brain awake.", "L'eau garde le corps frais et le cerveau réveillé.",
        "Aim for 6–8 cups a day; more on hot days or after sport.", "Viser 6 à 8 verres par jour ; plus s'il fait chaud ou après le sport.",
        ["A cup at each meal", "Sip after sport", "Carry a small bottle"],
        ["Un verre à chaque repas", "Boire après le sport", "Porter une petite bouteille"]),
      T("Sleep and rest", "Le sommeil et le repos",
        "Sleep is when the body and brain repair.", "Le sommeil, c'est quand le corps et le cerveau se réparent.",
        "Children need 9–12 hours. A calm bedtime routine helps the body fall asleep.", "Les enfants ont besoin de 9 à 12 heures. Une routine douce aide à s'endormir.",
        ["Same bedtime each night", "Lights low, voices low", "Story + breath = sleep"],
        ["Même heure chaque soir", "Lumières basses, voix basses", "Histoire + respiration = sommeil"]),
      T("Body safety: yes/no touch", "Sécurité corporelle : touches oui/non",
        "Your body belongs to you. Some touches feel safe; some do not.", "Ton corps t'appartient. Certaines touches sont sûres ; d'autres non.",
        "If a touch feels unsafe, say no, walk away, tell a trusted adult.", "Si une touche n'est pas sûre, dire non, s'éloigner, prévenir un adulte de confiance.",
        ["Saying no is okay", "Tell a trusted adult", "Privacy in the bathroom"],
        ["Dire non est permis", "Le dire à un adulte de confiance", "L'intimité dans la salle de bain"]),
      T("Feelings and the body", "Les émotions et le corps",
        "Big feelings show up in the body before we have words.", "Les grandes émotions apparaissent dans le corps avant les mots.",
        "Hot cheeks, tight tummy, fast breath are signals — not danger.", "Joues chaudes, ventre serré, respiration rapide sont des signaux — pas un danger.",
        ["Cheeks hot = upset", "Tummy tight = worried", "Breath fast = excited"],
        ["Joues chaudes = contrarié", "Ventre serré = inquiet", "Respiration rapide = excité"]),
      T("Coughs, colds and germs", "Toux, rhumes et microbes",
        "Germs are tiny and travel by touch, droplets and surfaces.", "Les microbes sont minuscules et voyagent par contact, gouttelettes et surfaces.",
        "Cover the cough, wash hands, rest at home if sick.", "Tousser dans le coude, se laver les mains, se reposer si malade.",
        ["Cough into the elbow", "Tissue in the bin", "Stay home when fever"],
        ["Tousser dans le coude", "Mouchoir à la poubelle", "Rester chez soi si fièvre"]),
      T("Safe at home and on the road", "Sécurité à la maison et dans la rue",
        "Safety means choices that protect our body.", "La sécurité, ce sont des choix qui protègent notre corps.",
        "Hold an adult's hand near roads, look both ways, walk — don't run — across.", "Tenir la main près des routes, regarder des deux côtés, traverser en marchant.",
        ["Stop, look, listen", "Cross at zebra", "No playing near stoves"],
        ["S'arrêter, regarder, écouter", "Traverser au passage piéton", "Pas de jeu près des plaques de cuisson"]),
      T("Visiting the doctor", "Aller chez le médecin",
        "Doctors and nurses help us stay well and heal when sick.", "Le médecin et l'infirmière nous aident à rester en forme et à guérir.",
        "They will explain each step; you can always ask questions.", "Ils expliquent chaque étape ; on peut toujours poser des questions.",
        ["Tell where it hurts", "Breathe slow for the stethoscope", "Ask any question"],
        ["Dire où ça fait mal", "Respirer doucement avec le stéthoscope", "Poser toute question"]),
    ],
  },
  {
    slug: "civics",
    title: { en: "Civics & Values", fr: "Éducation civique et valeurs" },
    blurb: { en: "Kindness, fairness and belonging — learned together.", fr: "Bienveillance, justice et appartenance — apprises ensemble." },
    topics: [
      T("Rules at home and school", "Les règles à la maison et à l'école",
        "Rules are agreements that keep people safe and fair.", "Les règles sont des accords qui assurent sécurité et justice.",
        "Rules change with the place, but the reason is the same: take care of each other.", "Les règles changent selon les lieux, mais l'idée reste : prendre soin les uns des autres.",
        ["Quiet when others sleep", "Wait your turn to speak", "Pack away after play"],
        ["Silence quand les autres dorment", "Attendre son tour pour parler", "Ranger après le jeu"]),
      T("Rights and responsibilities", "Droits et responsabilités",
        "A right is something you should always have; a responsibility is something you do for others.", "Un droit est ce qu'on doit avoir ; une responsabilité est ce qu'on fait pour les autres.",
        "They go together: my right to be safe is your responsibility to be kind, and vice versa.", "Ils vont ensemble : mon droit d'être en sécurité, c'est ta responsabilité d'être bienveillant.",
        ["Right: to learn", "Right: to be safe", "Responsibility: to listen"],
        ["Droit : apprendre", "Droit : être en sécurité", "Responsabilité : écouter"]),
      T("Sharing and taking turns", "Partager et attendre son tour",
        "Sharing means making room for others to use what we have.", "Partager, c'est laisser de la place aux autres.",
        "Taking turns is sharing in time: my turn now, your turn next.", "Attendre son tour, c'est partager dans le temps : à moi maintenant, à toi ensuite.",
        ["Share the crayons", "Use a sand timer", "Say your friend's name when it's their turn"],
        ["Partager les crayons", "Utiliser un sablier", "Dire le prénom de l'ami à son tour"]),
      T("Kindness and empathy", "Bienveillance et empathie",
        "Kindness is choosing words and actions that lift others.", "La bienveillance, ce sont les mots et gestes qui élèvent les autres.",
        "Empathy is feeling with someone — noticing what they feel and showing you understand.", "L'empathie, c'est ressentir avec quelqu'un et lui montrer qu'on comprend.",
        ["Help a friend stand up", "Listen without interrupting", "Say sorry from the heart"],
        ["Aider un ami à se lever", "Écouter sans couper la parole", "Dire pardon sincèrement"]),
      T("My country and its flag", "Mon pays et son drapeau",
        "A country is the place where we live with shared laws and symbols.", "Un pays est l'endroit où nous vivons avec des lois et des symboles communs.",
        "A flag is a symbol made of colours and shapes that mean something to its people.", "Un drapeau est un symbole de couleurs et de formes qui ont du sens pour son peuple.",
        ["Name my country", "Describe my flag", "Greet in our national language"],
        ["Nommer mon pays", "Décrire mon drapeau", "Saluer dans notre langue nationale"]),
      T("Community helpers", "Les métiers d'aide",
        "Helpers are the people whose work keeps a community safe and well.", "Les aidants sont les personnes dont le travail rend la communauté sûre et heureuse.",
        "We thank them by being polite, careful, and grateful.", "On les remercie en étant polis, prudents et reconnaissants.",
        ["Nurse heals", "Teacher teaches", "Bus driver carries us"],
        ["L'infirmière soigne", "L'enseignant enseigne", "Le chauffeur nous transporte"]),
      T("Belonging to a group", "Appartenir à un groupe",
        "Belonging is feeling that we matter in a group.", "Appartenir, c'est sentir qu'on compte dans un groupe.",
        "Groups have names, signs and stories. Belonging does not mean being the same.", "Les groupes ont des noms, des signes, des histoires. Appartenir ne veut pas dire être identique.",
        ["My family", "My class", "My neighbourhood"],
        ["Ma famille", "Ma classe", "Mon quartier"]),
      T("Solving small conflicts", "Résoudre les petits conflits",
        "A conflict is when two people want different things.", "Un conflit, c'est quand deux personnes veulent des choses différentes.",
        "Steps: stop, speak softly, listen, find a solution together.", "Étapes : s'arrêter, parler doucement, écouter, trouver une solution ensemble.",
        ["Use I-messages: I felt…", "Take turns talking", "Agree on a fair plan"],
        ["Dire « je » : j'ai ressenti…", "Parler à tour de rôle", "S'accorder sur une solution juste"]),
      T("Caring for shared places", "Prendre soin des lieux partagés",
        "Shared places (school, park, classroom) belong to everyone.", "Les lieux partagés (école, parc, classe) appartiennent à tous.",
        "Leave them as clean — or cleaner — than we found them.", "Les laisser aussi propres — ou plus — qu'on les a trouvés.",
        ["Throw rubbish in the bin", "Push the chair under the desk", "Wipe the table after eating"],
        ["Jeter à la poubelle", "Pousser sa chaise sous le bureau", "Nettoyer la table après manger"]),
      T("Honesty and trust", "Honnêteté et confiance",
        "Honesty is telling the truth, even when it is hard.", "L'honnêteté, c'est dire la vérité, même quand c'est difficile.",
        "Trust grows when our words match our actions over time.", "La confiance grandit quand les mots et les actes se ressemblent.",
        ["Own up to a mistake", "Return what is not yours", "Keep a small promise"],
        ["Reconnaître une erreur", "Rendre ce qui n'est pas à soi", "Tenir une petite promesse"]),
    ],
  },
  {
    slug: "cultural-studies",
    title: { en: "Cultural Studies", fr: "Études culturelles" },
    blurb: { en: "Stories, food and traditions of our many homes.", fr: "Récits, cuisine et traditions de nos nombreuses maisons." },
    topics: [
      T("What is culture?", "Qu'est-ce que la culture ?",
        "Culture is the shared way a group of people live: language, food, music, beliefs.", "La culture, c'est la façon partagée de vivre d'un groupe : langue, nourriture, musique, croyances.",
        "Every person belongs to several cultures at once — family, country, age group.", "Chaque personne appartient à plusieurs cultures à la fois — famille, pays, génération.",
        ["My family's special meal", "Our greeting at home", "A song my grandparent sings"],
        ["Le plat spécial de ma famille", "Notre salutation à la maison", "Une chanson de mon grand-parent"]),
      T("Family languages and names", "Langues et prénoms de famille",
        "Names often carry a story or a wish from family.", "Les prénoms portent souvent une histoire ou un vœu familial.",
        "Many homes speak more than one language; that is a treasure, not a problem.", "Beaucoup de familles parlent plusieurs langues ; c'est une richesse, pas un problème.",
        ["What does my name mean?", "Who chose my name?", "Which languages do we speak?"],
        ["Que signifie mon prénom ?", "Qui a choisi mon prénom ?", "Quelles langues parlons-nous ?"]),
      T("Food we share at home", "La nourriture que l'on partage",
        "Food is one of the strongest signs of culture.", "La nourriture est l'un des plus forts symboles culturels.",
        "Recipes travel with families and change a little each generation.", "Les recettes voyagent avec les familles et évoluent un peu à chaque génération.",
        ["Rice and beans", "Plantain", "Couscous"],
        ["Riz et haricots", "Plantain", "Couscous"]),
      T("Festivals and celebrations", "Fêtes et célébrations",
        "A festival is a special day many people celebrate together.", "Une fête est un jour spécial célébré ensemble.",
        "Festivals often involve food, music, clothes and stories.", "Les fêtes mêlent souvent nourriture, musique, vêtements et récits.",
        ["New Year", "Eid", "Christmas / Noël"],
        ["Nouvel An", "Aïd", "Noël / Christmas"]),
      T("Folktales and proverbs", "Contes et proverbes",
        "Folktales are stories handed down to teach lessons gently.", "Les contes sont des histoires transmises pour enseigner avec douceur.",
        "Proverbs are short sentences full of wisdom; they fit in the palm of the mind.", "Les proverbes sont de courtes phrases pleines de sagesse ; ils tiennent dans la paume de l'esprit.",
        ["The tortoise and the hare", "It takes a village…", "Slow and steady wins"],
        ["Le lièvre et la tortue", "Il faut un village…", "Tout doucement, on y arrive"]),
      T("Clothes and ceremonies", "Vêtements et cérémonies",
        "Clothes can show belonging, respect or celebration.", "Les vêtements peuvent dire l'appartenance, le respect ou la fête.",
        "Ceremonial dress is often inherited and full of meaning.", "Les tenues de cérémonie sont souvent héritées et pleines de sens.",
        ["Wedding clothes", "Sunday best", "Traditional wrappers"],
        ["Tenue de mariage", "Tenue du dimanche", "Pagnes traditionnels"]),
      T("Music and dance traditions", "Traditions de musique et de danse",
        "Each culture has rhythms and steps that belong to its history.", "Chaque culture a ses rythmes et ses pas liés à son histoire.",
        "Learning a dance is learning a story with the body.", "Apprendre une danse, c'est apprendre une histoire avec le corps.",
        ["Soukous", "Highlife", "Salsa"],
        ["Soukous", "Highlife", "Salsa"]),
      T("Religions of the world (kindly)", "Les religions du monde (avec respect)",
        "Religions are sets of beliefs and rituals about life's biggest questions.", "Les religions sont des croyances et rites sur les grandes questions de la vie.",
        "We learn about them with curiosity and respect, even if we don't share them.", "On les découvre avec curiosité et respect, même si on ne les partage pas.",
        ["Christianity / Christianisme", "Islam / Islam", "Indigenous beliefs"],
        ["Christianisme / Christianity", "Islam / Islam", "Croyances autochtones"]),
      T("Traditional games", "Jeux traditionnels",
        "Traditional games use simple objects and a lot of imagination.", "Les jeux traditionnels utilisent peu d'objets et beaucoup d'imagination.",
        "Many games travel across countries with new names.", "Beaucoup de jeux voyagent d'un pays à l'autre sous d'autres noms.",
        ["Mancala", "Hopscotch / Marelle", "Skipping rope"],
        ["Awalé", "Marelle / Hopscotch", "Corde à sauter"]),
      T("My cultural ID card", "Ma carte d'identité culturelle",
        "Make a small card that tells who you are and where you come from.", "Fabriquer une petite carte qui dit qui tu es et d'où tu viens.",
        "Include name, languages, favourite food and a family story.", "Mettre prénom, langues, plat préféré et une histoire familiale.",
        ["Name + meaning", "Two languages I hear", "A family song"],
        ["Prénom + sens", "Deux langues que j'entends", "Une chanson de famille"]),
    ],
  },
  {
    slug: "geography",
    title: { en: "Geography", fr: "Géographie" },
    blurb: { en: "From our room to the wider world, gently.", fr: "De notre chambre au monde, en douceur." },
    topics: [
      T("My room is a map", "Ma chambre est une carte",
        "A map is a small drawing of a real place seen from above.", "Une carte est un petit dessin d'un lieu réel vu de haut.",
        "Draw the bed, the door, the window where they really are. That is your first map.", "Dessine le lit, la porte, la fenêtre à leur place. C'est ta première carte.",
        ["Top view of room", "Mark the door", "Show where you sleep"],
        ["Vue de dessus de la chambre", "Marquer la porte", "Indiquer où tu dors"]),
      T("Directions: N, S, E, W", "Les points cardinaux : N, S, E, O",
        "There are four main directions: north, south, east, west.", "Il y a quatre directions principales : nord, sud, est, ouest.",
        "The sun rises in the east, sets in the west. That gives the others.", "Le soleil se lève à l'est, se couche à l'ouest. Cela donne les autres.",
        ["Sun rises = east", "Sun sets = west", "If facing north, right = east"],
        ["Le soleil se lève à l'est", "Le soleil se couche à l'ouest", "Face au nord, à droite = est"]),
      T("Continents and oceans", "Continents et océans",
        "Earth has 7 continents and 5 oceans.", "La Terre compte 7 continents et 5 océans.",
        "Continents are huge pieces of land; oceans are huge bodies of salty water around them.", "Les continents sont d'énormes terres ; les océans sont d'immenses étendues d'eau salée autour.",
        ["Africa, Europe, Asia…", "Atlantic Ocean", "Pacific Ocean"],
        ["Afrique, Europe, Asie…", "Océan Atlantique", "Océan Pacifique"]),
      T("Rivers, lakes, oceans", "Rivières, lacs, océans",
        "These are the three main shapes of fresh and salt water.", "Voici les trois grandes formes d'eau douce et salée.",
        "Rivers move, lakes rest, oceans roar. Most rivers end in an ocean.", "Les rivières bougent, les lacs se reposent, les océans grondent. La plupart des rivières finissent dans un océan.",
        ["The Nile (river)", "Lake Tanganyika", "The Atlantic Ocean"],
        ["Le Nil (rivière)", "Lac Tanganyika", "L'océan Atlantique"]),
      T("Mountains, valleys, plains", "Montagnes, vallées, plaines",
        "Land takes different shapes: high (mountain), low (valley), flat (plain).", "La terre prend des formes : haute (montagne), basse (vallée), plate (plaine).",
        "Each shape changes the weather, the plants and the way people live.", "Chaque forme change la météo, les plantes et la vie des gens.",
        ["Mount Kilimanjaro", "The Rift Valley", "The Sahel plains"],
        ["Le Kilimandjaro", "La vallée du Rift", "Les plaines du Sahel"]),
      T("Weather and climate", "Météo et climat",
        "Weather is what happens today; climate is what usually happens over the year.", "La météo, c'est aujourd'hui ; le climat, c'est ce qui se passe en général sur l'année.",
        "Climate decides if we live with rain forests, deserts or snow.", "Le climat décide si on vit dans la forêt, le désert ou la neige.",
        ["Sunny day = weather", "Hot all year = tropical climate", "Cold winters = temperate climate"],
        ["Jour ensoleillé = météo", "Chaud toute l'année = climat tropical", "Hivers froids = climat tempéré"]),
      T("Where does the rain go?", "Où va la pluie ?",
        "Rain follows the water cycle: it falls, flows, then rises again.", "La pluie suit le cycle de l'eau : elle tombe, s'écoule, puis remonte.",
        "Rain → river → ocean → cloud → rain.", "Pluie → rivière → océan → nuage → pluie.",
        ["Puddles dry in the sun", "Rivers flow downhill", "Clouds form over warm water"],
        ["Les flaques sèchent au soleil", "Les rivières coulent vers le bas", "Les nuages se forment sur l'eau chaude"]),
      T("Maps and symbols", "Cartes et symboles",
        "Maps use small symbols to show real things.", "Les cartes utilisent des petits symboles pour montrer le réel.",
        "A blue line is a river, a green patch is a forest. The key explains them.", "Une ligne bleue = rivière, une zone verte = forêt. La légende explique.",
        ["Blue = water", "Green = forest", "Brown = mountain"],
        ["Bleu = eau", "Vert = forêt", "Marron = montagne"]),
      T("Cities, towns and villages", "Villes et villages",
        "These are places where people live, in different sizes.", "Ce sont des lieux où vivent les gens, de tailles différentes.",
        "Cities are very big, towns medium, villages small. Each has its own rhythm.", "Les villes sont très grandes, les bourgs moyens, les villages petits. Chacun a son rythme.",
        ["City: Kigali", "Town: my district", "Village: my grandparents'"],
        ["Ville : Kigali", "Bourg : mon quartier", "Village : chez mes grands-parents"]),
      T("My country on the globe", "Mon pays sur le globe",
        "A globe is a model of the Earth shaped like a ball.", "Le globe est un modèle de la Terre en forme de boule.",
        "Find your continent first, then your country, then your city.", "Trouve ton continent, puis ton pays, puis ta ville.",
        ["Find Africa first", "Find my country", "Find my city"],
        ["Trouver l'Afrique d'abord", "Trouver mon pays", "Trouver ma ville"]),
    ],
  },
  {
    slug: "environmental-science",
    title: { en: "Environmental Science", fr: "Sciences environnementales" },
    blurb: { en: "Care for the earth as a daily practice.", fr: "Prendre soin de la Terre, jour après jour." },
    topics: [
      T("Living and non-living things", "Êtres vivants et non vivants",
        "Living things grow, breathe and need food and water.", "Les vivants grandissent, respirent, ont besoin d'eau et de nourriture.",
        "Non-living things don't do these — but they can still matter (water, rocks, air).", "Les non-vivants ne le font pas — mais ils restent importants (eau, roches, air).",
        ["Plant: living", "Stone: non-living", "Bird: living"],
        ["Plante : vivant", "Pierre : non-vivant", "Oiseau : vivant"]),
      T("Plants need sun, soil, water", "Les plantes ont besoin de soleil, terre, eau",
        "A plant grows when these three are present and balanced.", "Une plante pousse si ces trois éléments sont équilibrés.",
        "Too much or too little of any one stops growth. Plants tell us by their leaves.", "Trop ou pas assez de l'un et la pousse s'arrête. Les feuilles nous le disent.",
        ["Bean seed in cotton", "Watch a sprout in 3 days", "Move pot to the sun"],
        ["Graine dans du coton", "Observer une pousse en 3 jours", "Mettre le pot au soleil"]),
      T("Animals around us", "Les animaux autour de nous",
        "Animals live in many places: home, farm, forest, water.", "Les animaux vivent dans beaucoup d'endroits : maison, ferme, forêt, eau.",
        "Each animal has a place that fits its needs — its habitat.", "Chaque animal a un lieu qui correspond à ses besoins — son habitat.",
        ["Dog at home", "Cow on a farm", "Fish in water"],
        ["Chien à la maison", "Vache à la ferme", "Poisson dans l'eau"]),
      T("Where does water come from?", "D'où vient l'eau ?",
        "Our water comes from rain, rivers, lakes and underground.", "Notre eau vient de la pluie, des rivières, des lacs et du sous-sol.",
        "It must be cleaned before drinking — boiled or filtered.", "Il faut la nettoyer avant de boire — bouillir ou filtrer.",
        ["Rainwater jar", "Tap at home", "Village well"],
        ["Jarre d'eau de pluie", "Robinet à la maison", "Puits du village"]),
      T("Saving water and electricity", "Économiser l'eau et l'électricité",
        "Saving means using only what we need.", "Économiser, c'est n'utiliser que le nécessaire.",
        "Small habits add up: tap closed, lights off, short showers.", "Les petits gestes comptent : robinet fermé, lumières éteintes, douches courtes.",
        ["Close tap while brushing", "Switch off lights", "Unplug when finished"],
        ["Fermer le robinet en se brossant", "Éteindre les lumières", "Débrancher après usage"]),
      T("Reduce, reuse, recycle", "Réduire, réutiliser, recycler",
        "These are three ways to make less rubbish.", "Trois façons de faire moins de déchets.",
        "Reduce first (buy less), reuse (use again), recycle last (turn into new things).", "D'abord réduire (acheter moins), puis réutiliser, enfin recycler.",
        ["Bring a bag to the market", "Reuse a glass jar", "Sort plastic for recycling"],
        ["Apporter un sac au marché", "Réutiliser un pot en verre", "Trier le plastique à recycler"]),
      T("Trees are quiet helpers", "Les arbres, des aides discrets",
        "Trees give shade, food, oxygen and homes for animals.", "Les arbres donnent de l'ombre, de la nourriture, de l'oxygène et des abris.",
        "Planting a tree is a kindness that grows for years.", "Planter un arbre, c'est une bonté qui grandit des années.",
        ["Plant a fruit tree", "Water it weekly", "Sit in its shade"],
        ["Planter un arbre fruitier", "L'arroser chaque semaine", "S'asseoir à son ombre"]),
      T("Pollution and how to fight it", "La pollution et comment la combattre",
        "Pollution is harmful waste in air, water or land.", "La pollution, ce sont des déchets nocifs dans l'air, l'eau ou le sol.",
        "We fight it by cleaning up, walking, sharing transport and using less plastic.", "On la combat en nettoyant, en marchant, en partageant les trajets, en réduisant le plastique.",
        ["Pick up litter in the park", "Walk for short trips", "Refuse single-use plastic"],
        ["Ramasser les déchets au parc", "Marcher pour les petits trajets", "Refuser le plastique jetable"]),
      T("Weather and seasons", "Météo et saisons",
        "Seasons are long patterns of weather over the year.", "Les saisons sont de longs cycles météo sur l'année.",
        "Each season changes plants, clothes and food on the table.", "Chaque saison change les plantes, les vêtements et la nourriture.",
        ["Rainy season → mango", "Dry season → harvest", "Cool months → soup"],
        ["Saison des pluies → mangue", "Saison sèche → récolte", "Mois frais → soupe"]),
      T("My green promise", "Ma promesse verte",
        "A green promise is a small daily action for the planet.", "Une promesse verte est une petite action quotidienne pour la planète.",
        "Pick one. Do it every day for a week. Notice how it feels.", "En choisir une. La faire chaque jour pendant une semaine. Observer l'effet.",
        ["I close the tap", "I sort my rubbish", "I plant one seed"],
        ["Je ferme le robinet", "Je trie mes déchets", "Je plante une graine"]),
    ],
  },
];

export const richSubjectBySlug = (slug: string) => richSubjects.find((s) => s.slug === slug);
