import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { ArrowLeft, ShieldCheck } from "lucide-react";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy - KUA" },
      { name: "description", content: "How KUA protects caregiver and child data - plainly explained." },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <AppShell title="Privacy Policy" subtitle="Plain language. Last updated May 2026.">
      <Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
        <ArrowLeft className="h-4 w-4" /> Back home
      </Link>

      <div className="rounded-3xl border border-border/60 bg-card p-7 shadow-soft md:p-10">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-primary-soft px-3 py-1 text-xs font-semibold text-primary">
          <ShieldCheck className="h-3.5 w-3.5" /> Your trust matters
        </div>

        <Section title="What we collect">
          <p>When you create an account we store your email, your caregiver name and role, and your child's preferred name. We also keep things you enter inside the app - moods, notes, saved places, screening test results.</p>
        </Section>
        <Section title="What we do NOT collect">
          <ul className="list-disc pl-5 space-y-1">
            <li>We do not sell your data. Ever.</li>
            <li>We do not share your child's identifying information with third parties.</li>
            <li>We do not run advertising trackers.</li>
          </ul>
        </Section>
        <Section title="How your data is stored">
          <p>Data lives in our secure backend (Lovable Cloud, powered by Supabase) with row-level security so only you can read your records. Notes saved in the on-device vault never leave your device.</p>
        </Section>
        <Section title="Your child's information">
          <p>The child's name is used only to personalise greetings and reports inside the app. You can edit or remove it anytime from <Link to="/profile" className="text-primary underline">Profile</Link>.</p>
        </Section>
        <Section title="AI features">
          <p>Some calming reflections and sentence helpers are generated by an AI model. We send only the minimum context needed (e.g. selected card words). We do not send your child's name to AI providers.</p>
        </Section>
        <Section title="Your rights">
          <p>You can request export or deletion of your account at any time from <Link to="/settings" className="text-primary underline">Settings</Link>, or by contacting <a href="mailto:hello@kua.app" className="text-primary underline">hello@kua.app</a>.</p>
        </Section>
        <Section title="Children & medical use">
          <p>KUA is an educational companion, not a medical device. Screening tests are not diagnostic. Always consult a qualified professional for clinical questions.</p>
        </Section>
        <Section title="Contact">
          <p>Questions? Reach us at <a href="mailto:hello@kua.app" className="text-primary underline">hello@kua.app</a>.</p>
        </Section>
      </div>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-6 first:mt-0">
      <h2 className="font-display text-lg font-bold">{title}</h2>
      <div className="mt-2 text-sm leading-relaxed text-foreground/85">{children}</div>
    </section>
  );
}
