/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as FaithRouteImport } from './routes/faith'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as BreathingRouteImport } from './routes/breathing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as JourneySlugRouteImport } from './routes/journey.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiHelpRouteImport } from './routes/api/help'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithRoute = FaithRouteImport.update({
  id: '/faith',
  path: '/faith',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const BreathingRoute = BreathingRouteImport.update({
  id: '/breathing',
  path: '/breathing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TestsRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneySlugRoute = JourneySlugRouteImport.update({
  id: '/journey/$slug',
  path: '/journey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpRoute = ApiHelpRouteImport.update({
  id: '/api/help',
  path: '/api/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/communication': typeof CommunicationRoute
  '/faith': typeof FaithRoute
  '/growth': typeof GrowthRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRouteWithChildren
  '/today': typeof TodayRoute
  '/vault': typeof VaultRoute
  '/wheel': typeof WheelRoute
  '/wins': typeof WinsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/help': typeof ApiHelpRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/communication': typeof CommunicationRoute
  '/faith': typeof FaithRoute
  '/growth': typeof GrowthRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRouteWithChildren
  '/today': typeof TodayRoute
  '/vault': typeof VaultRoute
  '/wheel': typeof WheelRoute
  '/wins': typeof WinsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/help': typeof ApiHelpRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/communication': typeof CommunicationRoute
  '/faith': typeof FaithRoute
  '/growth': typeof GrowthRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRouteWithChildren
  '/today': typeof TodayRoute
  '/vault': typeof VaultRoute
  '/wheel': typeof WheelRoute
  '/wins': typeof WinsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/help': typeof ApiHelpRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/journey/$slug': typeof JourneySlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/breathing'
    | '/caregiver'
    | '/communication'
    | '/faith'
    | '/growth'
    | '/map'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/today'
    | '/vault'
    | '/wheel'
    | '/wins'
    | '/api/ai'
    | '/api/help'
    | '/article/$slug'
    | '/journey/$slug'
    | '/learn/$slug'
    | '/tests/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/breathing'
    | '/caregiver'
    | '/communication'
    | '/faith'
    | '/growth'
    | '/map'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/today'
    | '/vault'
    | '/wheel'
    | '/wins'
    | '/api/ai'
    | '/api/help'
    | '/article/$slug'
    | '/journey/$slug'
    | '/learn/$slug'
    | '/tests/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/breathing'
    | '/caregiver'
    | '/communication'
    | '/faith'
    | '/growth'
    | '/map'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/today'
    | '/vault'
    | '/wheel'
    | '/wins'
    | '/api/ai'
    | '/api/help'
    | '/article/$slug'
    | '/journey/$slug'
    | '/learn/$slug'
    | '/tests/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BreathingRoute: typeof BreathingRoute
  CaregiverRoute: typeof CaregiverRoute
  CommunicationRoute: typeof CommunicationRoute
  FaithRoute: typeof FaithRoute
  GrowthRoute: typeof GrowthRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestsRoute: typeof TestsRouteWithChildren
  TodayRoute: typeof TodayRoute
  VaultRoute: typeof VaultRoute
  WheelRoute: typeof WheelRoute
  WinsRoute: typeof WinsRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiHelpRoute: typeof ApiHelpRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  JourneySlugRoute: typeof JourneySlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith': {
      id: '/faith'
      path: '/faith'
      fullPath: '/faith'
      preLoaderRoute: typeof FaithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathing': {
      id: '/breathing'
      path: '/breathing'
      fullPath: '/breathing'
      preLoaderRoute: typeof BreathingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof TestsRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$slug': {
      id: '/journey/$slug'
      path: '/journey/$slug'
      fullPath: '/journey/$slug'
      preLoaderRoute: typeof JourneySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/help': {
      id: '/api/help'
      path: '/api/help'
      fullPath: '/api/help'
      preLoaderRoute: typeof ApiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestsRouteChildren {
  TestsSlugRoute: typeof TestsSlugRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsSlugRoute: TestsSlugRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BreathingRoute: BreathingRoute,
  CaregiverRoute: CaregiverRoute,
  CommunicationRoute: CommunicationRoute,
  FaithRoute: FaithRoute,
  GrowthRoute: GrowthRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestsRoute: TestsRouteWithChildren,
  TodayRoute: TodayRoute,
  VaultRoute: VaultRoute,
  WheelRoute: WheelRoute,
  WinsRoute: WinsRoute,
  ApiAiRoute: ApiAiRoute,
  ApiHelpRoute: ApiHelpRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  JourneySlugRoute: JourneySlugRoute,
  LearnSlugRoute: LearnSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
